cart/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$',
        views.cart_add,
        name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$',
        views.cart_remove,
        name='cart_remove'),
]

flyboard/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^', include('shop.urls', namespace='shop')),
    url(r'^accounts/', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from . import views, auth_views
from rest_framework.urlpatterns import format_suffix_patterns
urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
    url(r'^accounts/login/$', auth_views.login, name='login'),
    url(r'^accounts/logout/$', auth_views.logout, name='logout'),
    url(r'^accounts/password_change/$', auth_views.password_change, name='password_change'),
    url(r'^accounts/password_change/done/$', auth_views.password_change_done, name='password_change_done'),
    url(r'^accounts/password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^accounts/password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^accounts/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^accounts/reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^accounts/signup/$', auth_views.signup, name='signup'),
    url(r'^products_json/', views.ProductList.as_view()),
]
urlpatterns = format_suffix_patterns(urlpatterns)

shop/models.py
from django.db import models
from .converter import convert

# Create your models here.
from django.db import models
from django.core.urlresolvers import reverse

class Category(models.Model):
    name = models.CharField(max_length=200,db_index=True)
    slug = models.SlugField(max_length=200,db_index=True,unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                   args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

    def get_price(self,f):
        val = convert(self.price, "USD", str(f))
        return float(val(len(val) - 1))

shop/forms.py
from __future__ import unicode_literals

import unicodedata

from django import forms
from django.contrib.auth import (
    authenticate, get_user_model, password_validation,
)
from django.contrib.auth.models import User
from django.utils.translation import ugettext, ugettext_lazy as _

UserModel = get_user_model()


class UsernameField(forms.CharField):
    def to_python(self, value):
        return unicodedata.normalize('NFKC', super(UsernameField, self).to_python(value))

class UserCreationForm(forms.ModelForm):
    """
    A form that creates a user, with no privileges, from the given username and
    password.
    """
    error_messages = {
        'password_mismatch': _("The two password fields didn't match."),
    }
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput,
        help_text=password_validation.password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput,
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

    class Meta:
        model = User
        fields = ("username", "email")
        field_classes = {'username': UsernameField}

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        if self._meta.model.USERNAME_FIELD in self.fields:
            self.fields[self._meta.model.USERNAME_FIELD].widget.attrs.update({'autofocus': True})

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        self.instance.username = self.cleaned_data.get('username')
        password_validation.validate_password(self.cleaned_data.get('password2'), self.instance)
        return password2

    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.temp import CartAddProductForm
from django.contrib.auth.decorators import login_required
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import ProductSerializer


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    #products = products.filter(category=category)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/Products/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})
@login_required
def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/Products/detail.html',
                  {'product': product,'cart_product_form': cart_product_form})

# List at the end of the views.py
# Lists all products
class ProductList(APIView):

    def get(self,request):
        products_json = Product.objects.all()
        serializer = ProductSerializer(products_json, many=True)
        return Response(serializer.data)

shop/templates/files/logged_out.html
{% extends "shop/base.html" %}
{% load i18n %}


{% block content %}\
    <div class="container">
        <br/>
        <h2>Logged Out</h2>
        <p>{% trans " Thank you for spending some quality time with the Web site today." %}</p>

        <p><a href="{% url 'shop:login' %}">{% trans 'Log in again' %}</a></p>
    </div>
{% endblock %}

shop/templates/files/login.html
{% extends "shop/base.html" %}
{% block content %}

<div class="container">
<br/>
    {% if form.errors %}
        <p class="alert alert-danger">Your username and password didn't match. Please try again.</p>
    {% endif %}
{% if next %}
    {% if user.is_authenticated %}
    <p class=".alert-warning">Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<div class="wrapper">
    <form class="form-signin" method="post" action="{% url 'shop:login' %}">
        {% csrf_token %}
      <h2 class="form-signin-heading">Please login</h2>
      <input type="text" class="form-control" name="username" placeholder="User Name" required="" autofocus="" />
      <input type="password" class="form-control" name="password" placeholder="Password" required=""/>
      <input class="btn btn-lg btn-primary btn-block"  value="login" type="submit"/>
        <a href="{% url 'shop:signup' %}" class="signup ">New User</a>
        <input type="hidden" name="next" value="{{ next }}"/>
        	{# Assumes you setup the password_reset view in your URLconf #}
     <p><a href="{% url 'shop:password_reset' %}">Forgot password?</a></p>
    </form>

  </div>
    <div class="social">
        <ul>
            <li class="facebook"><a href="{% url "social:begin" "facebook"
            %}"><i class="fa fa-facebook-official" aria-hidden="true"></i> Sign in with Facebook</a></li>
        </ul>
    </div>

    </div>
{% endblock %}

shop/templates/files/password_change_done.html
{% extends "admin/base_site.html" %}
{% load i18n %}
{% block userlinks %}{% url 'django-admindocs-docroot' as docsroot %}{% if docsroot %}<a href="{{ docsroot }}">{% trans 'Documentation' %}</a> / {% endif %}{% trans 'Change password' %} / <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>{% endblock %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; {% trans 'Password change' %}
</div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}
{% block content %}
<p>{% trans 'Your password was changed.' %}</p>
{% endblock %}

shop/templates/files/password_change_form.html
{% extends "admin/base_site.html" %}
{% load i18n static %}
{% block extrastyle %}{{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static "admin/css/forms.css" %}"/>{% endblock %}
{% block userlinks %}{% url 'django-admindocs-docroot' as docsroot %}{% if docsroot %}
    <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> / {% endif %} {% trans 'Change password' %} /
    <a href="{% url 'admin:logout' %}">{% trans 'Log out' %}</a>{% endblock %}
{% block breadcrumbs %}
    <div class=" container breadcrumbs"><br/>
        <a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
        &rsaquo; {% trans 'Password change' %}
    </div>
{% endblock %}

{% block title %}{{ title }}{% endblock %}
{% block content_title %}<h1>{{ title }}</h1>{% endblock %}

{% block content %}
    <div id="content-main">

        <form method="post" class="sign-up">{% csrf_token %}
            <div>
                {% if form.errors %}
                    <p class="errornote">
                        {% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}
                            {% trans "Please correct the errors below." %}{% endif %}
                    </p>
                {% endif %}


                <p>{% trans "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}</p>

                <fieldset class="module aligned wide">

                    <div class="form-row">
                        {{ form.old_password.errors }}
                        {{ form.old_password.label_tag }} {{ form.old_password }}
                    </div>

                    <div class="form-row">
                        {{ form.new_password1.errors }}
                        {{ form.new_password1.label_tag }} {{ form.new_password1 }}
                        {% if form.new_password1.help_text %}
                            <p class="help">{{ form.new_password1.help_text|safe }}</p>
                        {% endif %}
                    </div>

                    <div class="form-row">
                        {{ form.new_password2.errors }}
                        {{ form.new_password2.label_tag }} {{ form.new_password2 }}
                        {% if form.new_password2.help_text %}
                            <p class="help">{{ form.new_password2.help_text|safe }}</p>
                        {% endif %}
                    </div>

                </fieldset>

                <div class="submit-row">
                    <input type="submit" value="{% trans 'Change my password' %}" class="default"/>
                </div>

            </div>
        </form>
    </div>
{% endblock %}

shop/templates/files/password_reset_complete.html
{% extends "shop/base.html" %}
{% load i18n %}


{% block content %}
<div>
    <h2>Password reset complete</h2>
</div>

<p>{% trans "Your password has been set.  You may go ahead and log in now." %}</p>

<p><a href="{{ login_url }}">{% trans 'Log in' %}</a></p>

{% endblock %}

shop/templates/files/password_reset_confirm.html
{% extends "shop/base.html" %}
{% load i18n %}


{% block content %}
    <div class="container">
        <br/>
        <div class="sign-up">
            <h2>Password reset confirmation</h2>
            {% if validlink %}
                <p>Please enter (and confirm) your new password.</p>
                <form action="" method="post">
                    <div style="display:none">
                        <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
                    </div>
                    <table>
                        <tr>
                            <td>{{ form.new_password1.errors }}
                                <label for="new_password1">New password:</label></td>
                            <td>{{ form.new_password1 }}</td>
                        </tr>
                        <tr>
                            <td>{{ form.new_password2.errors }}
                                <label for="new_password2">Confirm password:</label></td>
                            <td>{{ form.new_password2 }}</td>
                        </tr>
                        <tr>
                            <td></td>
                            <td><input type="submit" value="Change my password"/></td>
                        </tr>
                    </table>
                </form>
            {% else %}
                <h1>Password reset failed</h1>
                <p>The password reset link was invalid, possibly because it has already been used. Please request a new
                    password reset.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

shop/templates/files/password_reset_done.html
{% extends "shop/base.html" %}
{% load i18n %}


{% block content %}
    <div class="container">
        <br/>
        <div>
            <h2>Password reset send</h2>
        </div>


        <p>{% trans "We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly." %}</p>

        <p>{% trans "If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder." %}</p>
    </div>
{% endblock %}

shop/templates/files/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'shop:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

shop/templates/files/password_reset_form.html
{% extends "shop/base.html" %}
{% load i18n %}


{% block content %}
<div class="container">
    <h2>Reset Password</h2>
<p>{% trans "Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one." %}</p>

<form method="post">{% csrf_token %}
{{ form.email.errors }}
{% trans 'Email address:' %}</label> {{ form.email }} <input type="submit" value="{% trans 'Reset my password' %}" /></p>
</form>
</div>
{% endblock %}

shop/templates/files/signup.html
{% extends 'shop/base.html' %}

{% block content %}
    <div class="container">
        <br/>
        <h2>Sign up</h2>
        <form method="post" class="sign-up">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Sign up</button>
        </form>
    </div>
{% endblock %}